### ISSUE TITLE
Request for including wheel

### ISSUE THREAD

**Issue by simnow7** [akamai/AkamaiOPEN-edgegrid-python#23] opened 2016-08-12 02:22 UTC
Hi Master,
## When you release new version, please include wheel, otherwise Windows user have a issue as follows.

  building '_cffi_backend' extension
  error: Unable to find vcvarsall.bat

---

  **_Failed building wheel for cffi_**
  Running setup.py clean for cffi
Failed to build cryptography cffi
Installing collected packages: cffi, cryptography
##   Running setup.py install for cffi ... error

Sincerely,
Hwaseob

**Comment by robertolopezlopez** [comment] 2021-06-29 15:27
Hi @simnow7 ,

Thank you for reporting this issue. The problem is fixed in [release v1.1.1](https://pypi.org/project/edgegrid-python/1.1.1/). I will close this issue now, if you have further problems please create a new issue :-)

Regards,

Roberto

**Closed by robertolopezlopez** 2021-06-29 15:27 UTC
